### PR TITLE
Added support for custom SSH ports

### PR DESCRIPTION
**Pull request by jdsimcoe**
I also updated the README file to reflect this new field I added. I also made sure to incorporate your latest changes.

### CODE REVIEW

**Comment by getdave** [comment]
I appreciate this pull request. I promise to review it asap.

**Comment by jdsimcoe** [comment]
Cool.

## 

_I am one of *_thesimcoes.net→ http://thesimcoes.net/*

_dtr.mn→_  http://dtr.mn/_with me to know Jesus_

**Comment by getdave** [comment]
@jsimcoe Could you possibly amend the commit to go into "develop" branch please? Much appreciated.

**Comment by getdave** [comment]
@jsimcoe Any chance you could amend the commit destination as above? Much appreciated.

Also if you could close the pull request(s) that is/are no longer valid I'd really appreciate it.

**Comment by jdsimcoe** [comment]
Done. I tested it on one of my projects and it works like a champ.

## 

_I am one of *_thesimcoes.net→ http://thesimcoes.net/*

_dtr.mn→_  http://dtr.mn/_with me to know Jesus_

**Comment by jdsimcoe** [comment]
I also just made it so they if someone leaves the `ssh_port` off it will default to the SSH standard port of `22`. I also updated the README accordingly. Let me know if anything looks out of place.

**Comment by getdave** [comment]
Closing in favour of commits into the `develop` branch

**Pull request closed without merging**
